name = "moneytrack-api"
type = "javascript"

account_id = "e2956baafca3317c51c866d3efe65fb9"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

compatibility_date = "2023-06-14"

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "speriamo-pmbil"
